using Netaq.Domain.Common;
using Netaq.Domain.Enums;

namespace Netaq.Domain.Entities;

/// <summary>
/// A task assigned to a user in the Unified Task Center.
/// Auto-generated by the workflow engine when a step requires human interaction.
/// </summary>
public class UserTask : BaseEntity, ITenantEntity
{
    public Guid OrganizationId { get; set; }
    public Guid AssignedUserId { get; set; }
    public Guid WorkflowInstanceId { get; set; }
    public Guid WorkflowStepId { get; set; }
    
    public string TitleAr { get; set; } = string.Empty;
    public string TitleEn { get; set; } = string.Empty;
    public string? DescriptionAr { get; set; }
    public string? DescriptionEn { get; set; }
    
    public UserTaskStatus Status { get; set; } = UserTaskStatus.Pending;
    public TaskPriority Priority { get; set; } = TaskPriority.Medium;
    
    /// <summary>
    /// The entity this task relates to (e.g., Tender ID).
    /// </summary>
    public Guid? EntityId { get; set; }
    public string? EntityType { get; set; }
    
    /// <summary>
    /// SLA deadline for this task.
    /// </summary>
    public DateTime DueDate { get; set; }
    
    public SlaStatus SlaStatus { get; set; } = SlaStatus.OnTrack;
    
    public DateTime? CompletedAt { get; set; }
    
    /// <summary>
    /// If delegated, the original assignee.
    /// </summary>
    public Guid? DelegatedFromUserId { get; set; }
    
    // Navigation properties
    public Organization Organization { get; set; } = null!;
    public User AssignedUser { get; set; } = null!;
    public WorkflowInstance WorkflowInstance { get; set; } = null!;
    public WorkflowStep WorkflowStep { get; set; } = null!;
}
